INSERT INTO department (name)
VALUES  ("Offense"),
        ("Defense"),
        ("Special Teams");

INSERT INTO role (title, salary, department_id)
VALUES  ("Quarterback", 6610466.00, 1),
        ("Running Back", 2307988.00, 1),
        ("Wide Receiver", 3126653.00, 1),
        ("Tight End", 2488976.00, 1),
        ("Offensive Lineman", 3464310.00, 1),
        ("Defensive Lineman", 3435726.00, 2),
        ("Linebacker", 3063211.00, 2),
        ("Cornerback", 2554139, 2),
        ("Safety", 2903843, 2),
        ("Kicker", 2634590, 3),
        ("Punter", 1710553, 3);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ("Geno", "Smith", 1, NULL),
        ("Drew", "Lock", 1, 1),
        ("Kenneth", "Walker III", 2, NULL),
        ("DeeJay", "Dallas", 2, 3),
        ("Darwin", "Thompson", 2, 3),
        ("DK", "Metcalf", 3, NULL),
        ("Cade", "Johnson", 3, 6),
        ("Connor", "Wedington", 3, 6),
        ("Tyler", "Lockett", 3, NULL),
        ("Dareke", "Young", 3, 9),
        ("Dee", "Eskridge", 3, NULL),
        ("Cody", "Thompson", 3, 11),
        ("Noah", "Fant", 4, NULL),
        ("Colby", "Parkinson", 4, 13),
        ("Will", "Dissly", 4, 13),
        ("Tyler", "Mabry", 4, 13),
        ("Nick", "Bellore", 2, NULL),
        ("Charles", "Cross", 5, NULL),
        ("Jalen", "McKenzie", 5, 18),
        ("Damien", "Lewis", 5, NULL),
        ("Greg", "Eiland", 5, 20),
        ("Evan", "Brown", 5, NULL),
        ("Joey", "Hunt", 5, 22),
        ("Phil", "Haynes", 5, NULL),
        ("Jake", "Curhan", 5, 24),
        ("Abraham", "Lucas", 5, NULL),
        ("Stone", "Forsythe", 5, 26),
        ("Dre'Mont", "Jones", 6, NULL),
        ("Jarrod", "Hewitt", 6, 28),
        ("Bryan", "Mone", 6, NULL),
        ("Jarran", "Reed", 6, NULL),
        ("Myles", "Adams", 6, 31),
        ("Darrell", "Taylor", 7, NULL),
        ("Alton", "Robinson", 7, 33),
        ("Jordyn", "Brooks", 7, NULL),
        ("Nick", "Bellore", 7, 35),
        ("Joshua", "Onujiogu", 7, 35),
        ("Bobby", "Wagner", 7, NULL),
        ("Devin", "Bush", 7, 38),
        ("Jon", "Rhattigan", 7, 38),
        ("Uchenna", "Nwosu", 7, NULL),
        ("Boye", "Mafe", 7, 41),
        ("Tyreke", "Smith", 7, 41),
        ("Vi", "Jones", 7, 41),
        ("Mike", "Jackson", 8, NULL),
        ("Tre", "Brown", 8, 45),
        ("Isaiah", "Dunn", 8, 45),
        ("Chris", "Steele", 8, 45),
        ("Tariq", "Woolen", 8, NULL),
        ("Coby", "Bryant", 8, 49),
        ("Jamal", "Adams", 9, NULL),
        ("Quandre", "Diggs", 9, NULL),
        ("Julian", "Love", 9, 52),
        ("Joey", "Blount", 9, 52),
        ("Jason", "Myers", 10, NULL),
        ("Michael", "Dickson", 11, NULL)